<?php

namespace Database\Seeders;

use App\Models\Setup\Institution;
use Illuminate\Database\Seeder;

class InstitutionsSeeder extends Seeder
{
    public function run(): void
    {
        $institutions = [
            [
                'name' => 'University of Dar es Salaam',
                'institution_code' => 'UDSM',
                'registration_no' => 'TCU-UDSM',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Dar es Salaam',
                'district' => 'Ubungo',
                'ward' => 'Mlimani',
                'address' => 'Mlimani Campus, Dar es Salaam',
                'website' => 'https://www.udsm.ac.tz',
            ],
            [
                'name' => 'Sokoine University of Agriculture',
                'institution_code' => 'SUA',
                'registration_no' => 'TCU-SUA',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Morogoro',
                'district' => 'Morogoro',
                'ward' => 'SUA',
                'address' => 'Main Campus, Morogoro',
                'website' => 'https://www.sua.ac.tz',
            ],
            [
                'name' => 'Muhimbili University of Health and Allied Sciences',
                'institution_code' => 'MUHAS',
                'registration_no' => 'TCU-MUHAS',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Dar es Salaam',
                'district' => 'Ilala',
                'ward' => 'Upanga',
                'address' => 'United Nations Road, Upanga',
                'website' => 'https://www.muhas.ac.tz',
            ],
            [
                'name' => 'Open University of Tanzania',
                'institution_code' => 'OUT',
                'registration_no' => 'TCU-OUT',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Dar es Salaam',
                'district' => 'Kinondoni',
                'ward' => 'Mikocheni',
                'address' => 'Kawawa Road, Mikocheni',
                'website' => 'https://www.out.ac.tz',
            ],
            [
                'name' => 'University of Dodoma',
                'institution_code' => 'UDOM',
                'registration_no' => 'TCU-UDOM',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Dodoma',
                'district' => 'Dodoma',
                'ward' => 'Chimwaga',
                'address' => 'College Road, Dodoma',
                'website' => 'https://www.udom.ac.tz',
            ],
            [
                'name' => 'Ardhi University',
                'institution_code' => 'ARU',
                'registration_no' => 'TCU-ARU',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Dar es Salaam',
                'district' => 'Ubungo',
                'ward' => 'Observation Hill',
                'address' => 'University Road, Dar es Salaam',
                'website' => 'https://www.aru.ac.tz',
            ],
            [
                'name' => 'Nelson Mandela African Institution of Science and Technology',
                'institution_code' => 'NM-AIST',
                'registration_no' => 'TCU-NMAIST',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Arusha',
                'district' => 'Arusha',
                'ward' => 'Tengeru',
                'address' => 'Tengeru, Arusha',
                'website' => 'https://nm-aist.ac.tz',
            ],
            [
                'name' => 'Mzumbe University',
                'institution_code' => 'MU',
                'registration_no' => 'TCU-MU',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Morogoro',
                'district' => 'Mvomero',
                'ward' => 'Mzumbe',
                'address' => 'Mzumbe Campus, Morogoro',
                'website' => 'https://www.mzumbe.ac.tz',
            ],
            [
                'name' => 'St. Augustine University of Tanzania',
                'institution_code' => 'SAUT',
                'registration_no' => 'TCU-SAUT',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Mwanza',
                'district' => 'Nyamagana',
                'ward' => 'Malimbe',
                'address' => 'Mwanza Campus, Mwanza',
                'website' => 'https://www.saut.ac.tz',
            ],
            [
                'name' => 'Catholic University of Health and Allied Sciences',
                'institution_code' => 'CUHAS',
                'registration_no' => 'TCU-CUHAS',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Mwanza',
                'district' => 'Nyamagana',
                'ward' => 'Bugarika',
                'address' => 'Bugando Hill, Mwanza',
                'website' => 'https://www.bugando.ac.tz',
            ],
            [
                'name' => 'University of Iringa',
                'institution_code' => 'UOI',
                'registration_no' => 'TCU-UOI',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Iringa',
                'district' => 'Iringa',
                'ward' => 'Gangilonga',
                'address' => 'Iringa Municipality',
                'website' => 'https://www.uoi.ac.tz',
            ],
            [
                'name' => 'St. John\'s University of Tanzania',
                'institution_code' => 'SJUT',
                'registration_no' => 'TCU-SJUT',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Dodoma',
                'district' => 'Dodoma',
                'ward' => 'Mji Mpya',
                'address' => 'Area C, Dodoma',
                'website' => 'https://www.sjut.ac.tz',
            ],
            [
                'name' => 'Abdulrahman Al-Sumait University',
                'institution_code' => 'SUMAIT',
                'registration_no' => 'TCU-SUMAIT',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Zanzibar North',
                'district' => 'Kaskazini B',
                'ward' => 'Chukwani',
                'address' => 'Chukwani, Zanzibar',
                'website' => 'https://sumait.ac.tz',
            ],
            [
                'name' => 'Aga Khan University Tanzania',
                'institution_code' => 'AKU-TZ',
                'registration_no' => 'TCU-AKU',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Dar es Salaam',
                'district' => 'Kinondoni',
                'ward' => 'Masaki',
                'address' => 'Ocean Road, Dar es Salaam',
                'website' => 'https://www.aku.edu',
            ],
            [
                'name' => 'Zanzibar University',
                'institution_code' => 'ZU',
                'registration_no' => 'TCU-ZU',
                'tin' => 'N/A',
                'institution_type' => 'University',
                'region' => 'Zanzibar Urban/West',
                'district' => 'Mjini',
                'ward' => 'Tunguu',
                'address' => 'Tunguu, Zanzibar',
                'website' => 'https://zu.ac.tz',
            ],
            [
                'name' => 'Tanzania Public Service College',
                'institution_code' => 'TPSC',
                'registration_no' => 'REG/BTP/068',
                'tin' => 'N/A',
                'institution_type' => 'College',
                'region' => 'Mbeya',
                'district' => 'Mbeya City',
                'ward' => 'Iyunga',
                'address' => 'Mbeya Campus',
                'website' => 'https://www.utumishi.go.tz',
            ],
            [
                'name' => 'Bagamoyo Professional College',
                'institution_code' => 'BPC',
                'registration_no' => 'REG/BTP/142P',
                'tin' => 'N/A',
                'institution_type' => 'College',
                'region' => 'Pwani',
                'district' => 'Bagamoyo',
                'ward' => 'Dunda',
                'address' => 'Bagamoyo',
                'website' => 'https://www.nactvet.go.tz',
            ],
            [
                'name' => 'Karatu Health Training Institute',
                'institution_code' => 'KHTI',
                'registration_no' => 'REG/HAS/113',
                'tin' => 'N/A',
                'institution_type' => 'College',
                'region' => 'Arusha',
                'district' => 'Karatu',
                'ward' => 'Karatu',
                'address' => 'Karatu',
                'website' => 'https://www.nactvet.go.tz',
            ],
            [
                'name' => 'Mpanda College of Health and Allied Sciences',
                'institution_code' => 'MCHAS',
                'registration_no' => 'REG/HAS/219',
                'tin' => 'N/A',
                'institution_type' => 'College',
                'region' => 'Katavi',
                'district' => 'Mpanda',
                'ward' => 'Mpanda',
                'address' => 'Mpanda',
                'website' => 'https://www.nactvet.go.tz',
            ],
            [
                'name' => 'Shukrani Training College',
                'institution_code' => 'STC',
                'registration_no' => 'REG/BTP/170P',
                'tin' => 'N/A',
                'institution_type' => 'College',
                'region' => 'Mbeya',
                'district' => 'Mbeya City',
                'ward' => 'Forest',
                'address' => 'Mbeya',
                'website' => 'https://www.nactvet.go.tz',
            ],
            [
                'name' => 'Makumira Training Institute',
                'institution_code' => 'MTI',
                'registration_no' => 'REG/BTP/154',
                'tin' => 'N/A',
                'institution_type' => 'College',
                'region' => 'Arusha',
                'district' => 'Meru',
                'ward' => 'Usa River',
                'address' => 'Makumira, Arusha',
                'website' => 'https://www.nactvet.go.tz',
            ],
            [
                'name' => 'Kibosho Vocational Training Centre',
                'institution_code' => 'KVTC',
                'registration_no' => 'REG/NACTVET/0957P',
                'tin' => 'N/A',
                'institution_type' => 'College',
                'region' => 'Kilimanjaro',
                'district' => 'Moshi',
                'ward' => 'Kibosho',
                'address' => 'Kibosho, Moshi',
                'website' => 'https://www.nactvet.go.tz',
            ],
            [
                'name' => 'Namtumbo District Vocational Training Centre',
                'institution_code' => 'NDVTC',
                'registration_no' => 'REG/NACTVET/0648',
                'tin' => 'N/A',
                'institution_type' => 'College',
                'region' => 'Ruvuma',
                'district' => 'Namtumbo',
                'ward' => 'Namtumbo',
                'address' => 'Namtumbo, Ruvuma',
                'website' => 'https://www.nactvet.go.tz',
            ],
        ];

        foreach ($institutions as $institution) {
            Institution::query()->updateOrCreate(
                ['institution_code' => $institution['institution_code']],
                array_merge($institution, [
                    'created_by_user_id' => 1,
                    'is_active' => true,
                ])
            );
        }
    }
}
