<?php

namespace App\Swagger\Endpoints;

use OpenApi\Attributes as OA;

class SetupEndpoints
{
    #[OA\Get(path: "/api/setup/nationalities", tags: ["Setup Nationalities"], summary: "List setup nationalities", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/setup/nationalities", tags: ["Setup Nationalities"], summary: "Create setup nationality", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/setup/nationalities/{nationality}", tags: ["Setup Nationalities"], summary: "Show setup nationality", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "nationality", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/setup/nationalities/{nationality}", tags: ["Setup Nationalities"], summary: "Update setup nationality", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "nationality", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/setup/nationalities/{nationality}", tags: ["Setup Nationalities"], summary: "Delete setup nationality", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "nationality", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function setupNationalities(): void {}

    #[OA\Get(path: "/api/setup/permissions", tags: ["Permissions"], summary: "List permissions", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/setup/permissions", tags: ["Permissions"], summary: "Create permission", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/setup/permissions/{permission}", tags: ["Permissions"], summary: "Show permission", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "permission", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/setup/permissions/{permission}", tags: ["Permissions"], summary: "Update permission", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "permission", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/setup/permissions/{permission}", tags: ["Permissions"], summary: "Delete permission", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "permission", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function setupPermissions(): void {}

    #[OA\Get(path: "/api/setup/role-permissions", tags: ["Role Permissions"], summary: "List role permissions", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/setup/role-permissions", tags: ["Role Permissions"], summary: "Create role permission", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/setup/role-permissions/{role_permission}", tags: ["Role Permissions"], summary: "Show role permission", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "role_permission", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/setup/role-permissions/{role_permission}", tags: ["Role Permissions"], summary: "Update role permission", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "role_permission", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/setup/role-permissions/{role_permission}", tags: ["Role Permissions"], summary: "Delete role permission", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "role_permission", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function setupRolePermissions(): void {}

    #[OA\Get(path: "/api/designations", tags: ["Designations"], summary: "List designations", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/designations", tags: ["Designations"], summary: "Create designation", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/designations/{designation}", tags: ["Designations"], summary: "Show designation", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "designation", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/designations/{designation}", tags: ["Designations"], summary: "Update designation", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "designation", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/designations/{designation}", tags: ["Designations"], summary: "Delete designation", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "designation", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function designations(): void {}

    #[OA\Get(path: "/api/admin-areas", tags: ["Admin Areas"], summary: "List admin areas", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/admin-areas", tags: ["Admin Areas"], summary: "Create admin area", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/admin-areas/{admin_area}", tags: ["Admin Areas"], summary: "Show admin area", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_area", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/admin-areas/{admin_area}", tags: ["Admin Areas"], summary: "Update admin area", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_area", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/admin-areas/{admin_area}", tags: ["Admin Areas"], summary: "Delete admin area", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_area", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function adminHierarchies(): void {}

    #[OA\Get(path: "/api/admin-hierarchy-level-sections", tags: ["Admin Hierarchy Level Sections"], summary: "List admin hierarchy level sections", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/admin-hierarchy-level-sections", tags: ["Admin Hierarchy Level Sections"], summary: "Create admin hierarchy level section", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/admin-hierarchy-level-sections/{admin_hierarchy_level_section}", tags: ["Admin Hierarchy Level Sections"], summary: "Show admin hierarchy level section", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_hierarchy_level_section", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/admin-hierarchy-level-sections/{admin_hierarchy_level_section}", tags: ["Admin Hierarchy Level Sections"], summary: "Update admin hierarchy level section", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_hierarchy_level_section", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/admin-hierarchy-level-sections/{admin_hierarchy_level_section}", tags: ["Admin Hierarchy Level Sections"], summary: "Delete admin hierarchy level section", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_hierarchy_level_section", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function adminHierarchyLevelSections(): void {}

    #[OA\Get(path: "/api/admin-hierarchy-levels", tags: ["Admin Hierarchy Levels"], summary: "List admin hierarchy levels", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/admin-hierarchy-levels", tags: ["Admin Hierarchy Levels"], summary: "Create admin hierarchy level", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/admin-hierarchy-levels/{admin_hierarchy_level}", tags: ["Admin Hierarchy Levels"], summary: "Show admin hierarchy level", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_hierarchy_level", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/admin-hierarchy-levels/{admin_hierarchy_level}", tags: ["Admin Hierarchy Levels"], summary: "Update admin hierarchy level", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_hierarchy_level", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/admin-hierarchy-levels/{admin_hierarchy_level}", tags: ["Admin Hierarchy Levels"], summary: "Delete admin hierarchy level", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_hierarchy_level", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function adminHierarchyLevels(): void {}

    #[OA\Get(path: "/api/admin-hierarchy-sections", tags: ["Admin Hierarchy Sections"], summary: "List admin hierarchy sections", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/admin-hierarchy-sections", tags: ["Admin Hierarchy Sections"], summary: "Create admin hierarchy section", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/admin-hierarchy-sections/{admin_hierarchy_section}", tags: ["Admin Hierarchy Sections"], summary: "Show admin hierarchy section", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_hierarchy_section", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/admin-hierarchy-sections/{admin_hierarchy_section}", tags: ["Admin Hierarchy Sections"], summary: "Update admin hierarchy section", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_hierarchy_section", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/admin-hierarchy-sections/{admin_hierarchy_section}", tags: ["Admin Hierarchy Sections"], summary: "Delete admin hierarchy section", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "admin_hierarchy_section", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function adminHierarchySections(): void {}

    #[OA\Get(path: "/api/genders", tags: ["Genders"], summary: "List genders", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/genders", tags: ["Genders"], summary: "Create gender", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/genders/{gender}", tags: ["Genders"], summary: "Show gender", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "gender", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/genders/{gender}", tags: ["Genders"], summary: "Update gender", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "gender", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/genders/{gender}", tags: ["Genders"], summary: "Delete gender", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "gender", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function genders(): void {}

    #[OA\Get(path: "/api/identity-types", tags: ["Identity Types"], summary: "List identity types", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/identity-types", tags: ["Identity Types"], summary: "Create identity type", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/identity-types/{identity_type}", tags: ["Identity Types"], summary: "Show identity type", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "identity_type", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/identity-types/{identity_type}", tags: ["Identity Types"], summary: "Update identity type", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "identity_type", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/identity-types/{identity_type}", tags: ["Identity Types"], summary: "Delete identity type", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "identity_type", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function identityTypes(): void {}

    #[OA\Get(path: "/api/institutions", tags: ["Institutions"], summary: "List institutions", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/institutions", tags: ["Institutions"], summary: "Create institution", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/institutions/{institution}", tags: ["Institutions"], summary: "Show institution", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "institution", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/institutions/{institution}", tags: ["Institutions"], summary: "Update institution", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "institution", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/institutions/{institution}", tags: ["Institutions"], summary: "Delete institution", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "institution", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function institutions(): void {}

    #[OA\Get(path: "/api/licence-categories", tags: ["Licence Categories"], summary: "List licence categories", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/licence-categories", tags: ["Licence Categories"], summary: "Create licence category", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/licence-categories/{licence_category}", tags: ["Licence Categories"], summary: "Show licence category", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "licence_category", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/licence-categories/{licence_category}", tags: ["Licence Categories"], summary: "Update licence category", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "licence_category", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/licence-categories/{licence_category}", tags: ["Licence Categories"], summary: "Delete licence category", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "licence_category", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function licenceCategories(): void {}

    #[OA\Get(path: "/api/organization-types", tags: ["Organization Types"], summary: "List organization types", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/organization-types", tags: ["Organization Types"], summary: "Create organization type", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/organization-types/{organization_type}", tags: ["Organization Types"], summary: "Show organization type", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "organization_type", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/organization-types/{organization_type}", tags: ["Organization Types"], summary: "Update organization type", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "organization_type", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/organization-types/{organization_type}", tags: ["Organization Types"], summary: "Delete organization type", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "organization_type", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function organizationTypes(): void {}

    #[OA\Get(path: "/api/organization-units", tags: ["Organization Units"], summary: "List organization units", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/organization-units", tags: ["Organization Units"], summary: "Create organization unit", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/organization-units/{organization_unit}", tags: ["Organization Units"], summary: "Show organization unit", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "organization_unit", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/organization-units/{organization_unit}", tags: ["Organization Units"], summary: "Update organization unit", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "organization_unit", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/organization-units/{organization_unit}", tags: ["Organization Units"], summary: "Delete organization unit", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "organization_unit", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function organizationUnits(): void {}

    #[OA\Get(path: "/api/registration-types", tags: ["Registration Types"], summary: "List registration types", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/registration-types", tags: ["Registration Types"], summary: "Create registration type", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/registration-types/{registration_type}", tags: ["Registration Types"], summary: "Show registration type", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "registration_type", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/registration-types/{registration_type}", tags: ["Registration Types"], summary: "Update registration type", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "registration_type", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/registration-types/{registration_type}", tags: ["Registration Types"], summary: "Delete registration type", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "registration_type", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function registrationTypes(): void {}

    #[OA\Get(path: "/api/user-identifiers", tags: ["User Identifiers"], summary: "List user identifiers", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/user-identifiers", tags: ["User Identifiers"], summary: "Create user identifier", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/user-identifiers/{user_identifier}", tags: ["User Identifiers"], summary: "Show user identifier", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "user_identifier", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/user-identifiers/{user_identifier}", tags: ["User Identifiers"], summary: "Update user identifier", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "user_identifier", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/user-identifiers/{user_identifier}", tags: ["User Identifiers"], summary: "Delete user identifier", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "user_identifier", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function userIdentifiers(): void {}

    #[OA\Get(path: "/api/user-roles", tags: ["User Roles"], summary: "List user roles", security: [["sanctum" => []]], responses: [new OA\Response(response: 200, description: "List", content: new OA\JsonContent(ref: "#/components/schemas/PaginatedResponse"))])]
    #[OA\Post(path: "/api/user-roles", tags: ["User Roles"], summary: "Create user role", security: [["sanctum" => []]], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 201, description: "Created", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Get(path: "/api/user-roles/{user_role}", tags: ["User Roles"], summary: "Show user role", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "user_role", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Found", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    #[OA\Put(path: "/api/user-roles/{user_role}", tags: ["User Roles"], summary: "Update user role", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "user_role", in: "path", required: true, schema: new OA\Schema(type: "integer"))], requestBody: new OA\RequestBody(required: true, content: new OA\JsonContent(type: "object")), responses: [new OA\Response(response: 200, description: "Updated", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse"))])]
    #[OA\Delete(path: "/api/user-roles/{user_role}", tags: ["User Roles"], summary: "Delete user role", security: [["sanctum" => []]], parameters: [new OA\Parameter(name: "user_role", in: "path", required: true, schema: new OA\Schema(type: "integer"))], responses: [new OA\Response(response: 200, description: "Deleted", content: new OA\JsonContent(ref: "#/components/schemas/StandardResponse")), new OA\Response(response: 404, description: "Not found")])]
    public static function userRoles(): void {}

}
